---
# defaults file for aws-cloudigrade-cloudtrail
state: present
bucket_name: "{{ aws_prefix }}-cloudigrade-s3"
sqs_name: "{{ aws_prefix }}-cloudigrade-cloudtrail-sqs"
aws_region: us-east-1
bucket_state: "{{ state }}"
sqs_state: "{{ state }}"
bucket_arn: "arn:aws:s3:::{{ bucket_name }}"
verbose: false

sqs_policy: 
  Version: "2012-10-17"
  Id: "{{ sqs_name }}-policy-id"
  Statement:
    - Sid: "{{ sqs_name }}-statement-id"
      Effect: "Allow"
      Principal: 
        AWS: "*"
      Action: "SQS:SendMessage"
      Resource: "{{ queue.queue_arn }}"
      Condition:
        ArnLike: 
          aws:SourceArn: "{{ bucket_arn }}"

bucket_policy: 
  Version: "2012-10-17"
  Id: "{{ bucket_name }}-policy-id"
  Statement:
    - Sid: "{{ bucket_name }}-statement-id-allow-cloudtrail-get-acl"
      Effect: "Allow"
      Principal: 
        Service: "cloudtrail.amazonaws.com"
      Action: "s3:GetBucketAcl"
      Resource: "{{ bucket_arn }}"
    - Sid: "{{ bucket_name }}-statement-id-allow-cloudtrail-put-object"
      Effect: "Allow"
      Action: "s3:PutObject"
      Principal: 
        Service: "cloudtrail.amazonaws.com"
      Condition:
        StringEquals:
          s3:x-amz-acl: "bucket-owner-full-control"
      Resource: 
        - "{{ bucket_arn }}/AWSLogs/*"
