image: registry.gitlab.com/cloudigrade/images/deploy-container:latest

Test Templates:
  stage: test
  except:
    - master
    - tags
  before_script:
    - oc version
    - oc login ${KUBE_URL} --token=${KUBE_TOKEN}
  script:
    - kontemplate template ocp/local.yaml | oc apply --dry-run -f -
    - kontemplate template ocp/review.yaml | oc apply --dry-run -f -
    - kontemplate template ocp/test.yaml | oc apply --dry-run -f -
    - kontemplate template ocp/stage.yaml | oc apply --dry-run -f -
    - kontemplate template ocp/prod.yaml | oc apply --dry-run -f -

Test Ansible Playbooks:
  image: python:latest
  stage: test
  except:
    - master
    - tags
  before_script:
    - pip install ansible
  script:
    - ansible-playbook --syntax-check ansible/*.yaml
