os: osx
osx_image: xcode9.3

stages:
  - test
  - name: deploy
    if: (type IN (push)) AND ((branch = master) OR (tag IS present))

jobs:
  include:
    - stage: test
      if: (branch != master AND tag IS blank)
      before_install:
        - brew tap tazjin/kontemplate https://github.com/tazjin/kontemplate
        - brew install kontemplate https://raw.githubusercontent.com/Homebrew/homebrew-core/9d190ab350ce0b0d00d4968fed4b9fbe68a318ef/Formula/openshift-cli.rb
      before_script:
        - oc login https://api.insights.openshift.com --token=$OC_QE_TOKEN
      script:
        - kontemplate template ocp/local.yaml | oc apply --dry-run -f -
        - kontemplate template ocp/test.yaml | oc apply --dry-run -f -
    - stage: deploy
      before_install:
        - brew tap tazjin/kontemplate https://github.com/tazjin/kontemplate
        - brew install kontemplate https://raw.githubusercontent.com/Homebrew/homebrew-core/9d190ab350ce0b0d00d4968fed4b9fbe68a318ef/Formula/openshift-cli.rb
      before_script:
        - oc login https://api.insights.openshift.com --token=$OC_TEST_TOKEN
      script:
        - kontemplate template ocp/test.yaml | oc apply -f -
