---
global:
  env: local
  namespace: myproject
  fancyDomain: false
  fancyDomainTLS: false
  tls: false
include:
  - name: cloudigrade
    values:
      name: c1
      healthCheckHostHeader: health.cloudigrade.insights.openshiftapps.com
      api:
        enableImageChangeTrigger: true
        fancyRouteHost:
        repoUri: https://gitlab.com/cloudigrade/cloudigrade.git
        repoUriBranch: master
        imageStreamName: c1
        imageStreamTag: latest
        limits:
          container:
            cpuRequest:
            cpuLimit:
            memRequest:
            memLimit:
          build:
            cpuRequest:
            cpuLimit:
            memRequest:
            memLimit:
        replicaCount: 1
        routeHost: cloudigrade.127.0.0.1.nip.io
        routePath: /api/v1/
        sentry:
          enabled: false
      auth:
        fancyRouteHost:
        routeHost: cloudigrade.127.0.0.1.nip.io
        routePath: /auth/
      nginx:
        enableImageChangeTrigger: true
        repoUri: https://gitlab.com/cloudigrade/cloudigrade.git
        repoUriBranch: master
        repoContextDir: deployment/dev/
        baseImage: centos/nginx-112-centos7:latest
        imageStreamName: c1-nginx
        imageStreamTag: latest
        limits:
          container:
            cpuRequest:
            cpuLimit:
            memRequest:
            memLimit:
          build:
            cpuRequest:
            cpuLimit:
            memRequest:
            memLimit:
        port: 8080
      celery:
        enableImageChangeTrigger: true
        imageStreamName: c1
        imageStreamTag: latest
        beat:
          replicaCount: 1
          limits:
            container:
              cpuRequest:
              cpuLimit:
              memRequest:
              memLimit:
            build:
              cpuRequest:
              cpuLimit:
              memRequest:
              memLimit:
        sentry:
          enabled: false
        worker:
          replicaCount: 1
          limits:
            container:
              cpuRequest:
              cpuLimit:
              memRequest:
              memLimit:
            build:
              cpuRequest:
              cpuLimit:
              memRequest:
              memLimit:
      aws:
        sqs:
          defaultRegion: us-east-1
          accessKeyId: 123
          secretAccessKey: 456
          maxReceiveCount: 5
          namePrefix:
        defaultRegion: us-east-1
        accessKeyId: 123
        secretAccessKey: 456
        houndigrade:
          ecs:
            clusterName:
            imageName: registry.gitlab.com/cloudigrade/houndigrade
            imageTag: latest
            familyName: Houndigrade
          availabilityZone: us-east-1a
          autoscalingGroupName:
          scaleUpClusterSchedule: 300
          persistInspectionResultsSchedule: 300
          sentry:
            enabled: false
        cloudtrailEventUrl: https://sqs.us-east-1.amazonaws.com/123456789/test-cloudigrade-s3
        repopulateEc2InstanceMappingSchedule: 604800
        s3BucketName: test-cloudigrade-s3
        s3Lifecycle:
          name: s3_lifecycle_policy
          iaTransition: 30
          glacierTransition: 60
          maxAge: 1460
      django:
        debug: true
        allowedHosts: "*"
        settingsModule: config.settings.prod
        secretKey: local
      db:
        secretsFileName: postgresql
        databaseHost: postgresql.myproject.svc
        databaseName: postgres
        databaseUser: postgres
        databasePassword: postgres
        databasePort: 5432
      inspectPendingImagesMinAge: 43200
      inspectPendingImagesSchedule: 900
  - name: frontigrade
    values:
      name: f
      frontigrade:
        enableImageChangeTrigger: true
        repoUri: https://gitlab.com/cloudigrade/frontigrade.git
        repoUriBranch: master
        imageStreamName: f
        imageStreamTag: latest
        limits:
          container:
            cpuRequest:
            cpuLimit:
            memRequest:
            memLimit:
          build:
            cpuRequest:
            cpuLimit:
            memRequest:
            memLimit:
        port: 8080
        fancyRouteHost:
        replicaCount: 1
        routeHost: cloudigrade.127.0.0.1.nip.io
        routePath: /
        sentry:
          enabled: false
  - name: scaligrade
    values:
      name: s
      scaligrade:
        enableImageChangeTrigger: true
        repoUri: https://gitlab.com/cloudigrade/scaligrade.git
        repoUriBranch: master
        imageStreamName: s
        imageStreamTag: latest
        limits:
          container:
            cpuRequest:
            cpuLimit:
            memRequest:
            memLimit:
          build:
            cpuRequest:
            cpuLimit:
            memRequest:
            memLimit:
        port: 8080
        replicaCount: 1
        sentry:
          enabled: false
