---
global:
  env: prod
  namespace: cloudigrade-prod
  fancyDomain: true
  fancyDomainTLS: true
  tls: true
include:
  - name: cloudigrade
    values:
      name: c
      healthCheckHostHeader: health.cloudigrade.insights.openshiftapps.com
      api:
        enableImageChangeTrigger: true
        imageStreamName: c
        imageStreamTag: latest
        limits:
          container:
            cpuRequest: 100m
            cpuLimit: 200m
            memRequest: 256Mi
            memLimit: 512Mi
        replicaCount: 2
        replicaCountMax: 8
        sentry:
          enabled: true
        targetAverageCPUUtilization: 80
      nginx:
        enableImageChangeTrigger: true
        imageStreamName: c-nginx
        imageStreamTag: latest
        limits:
          container:
            cpuRequest: 100m
            cpuLimit: 100m
            memRequest: 64Mi
            memLimit: 128Mi
        port: 8080
      celery:
        enableImageChangeTrigger: true
        imageStreamName: c
        imageStreamTag: latest
        limits:
          container:
            cpuRequest: 300m
            cpuLimit: 500m
            memRequest: 512Mi
            memLimit: 1Gi
        beat:
          replicaCount: 1
          limits:
            container:
              cpuRequest: 100m
              cpuLimit: 100m
              memRequest: 64Mi
              memLimit: 128Mi
        sentry:
          enabled: true
        worker:
          replicaCount: 3
          replicaCountMax: 8
          targetAverageCPUUtilization: 80
          limits:
            container:
              cpuRequest: 100m
              cpuLimit: 200m
              memRequest: 256Mi
              memLimit: 512Mi
      aws:
        sqs:
          defaultRegion: us-east-1
          accessKeyId:
          secretAccessKey:
          namePrefix: prod-
          maxReceiveCount: 5
          maxYieldCount: 100
          maxHoundiYieldCount: 10
        defaultRegion: us-east-1
        accessKeyId:
        secretAccessKey:
        houndigrade:
          ecs:
            clusterName: cloudigrade-prod-us-east-1c
            imageName: registry.gitlab.com/cloudigrade/houndigrade
            imageTag: 0.2.0
            familyName: Houndigrade
          availabilityZone: us-east-1c
          autoscalingGroupName: EC2ContainerService-cloudigrade-prod-us-east-1c-EcsInstanceAsg-UZR9Y10ZTWKM
          scaleUpClusterSchedule: 3600
          persistInspectionResultsSchedule: 300
          sentry:
            enabled: true
        cloudtrailEventUrl:
        repopulateEc2InstanceMappingSchedule: 604800
        s3BucketName:
        s3Lifecycle:
          name: s3_lifecycle_policy
          iaTransition: 30
          glacierTransition: 60
          maxAge: 1460
      django:
        debug: false
        allowedHosts: '*'
        settingsModule: config.settings.prod
        secretKey:
      db:
        secretsFileName:
        databaseHost:
        databaseName:
        databasePort: 5432
        databaseUser:
        databasePassword:
      listener:
        enableImageChangeTrigger: true
        imageStreamName: c
        imageStreamTag: latest
        limits:
          container:
            cpuRequest: 100m
            cpuLimit: 200m
            memRequest: 128Mi
            memLimit: 256Mi
        replicaCount: 1
        logLevel: INFO
        topic: platform.sources.event-stream
        groupId: cloudmeter_prod
        server: platform-mq-prod-kafka-bootstrap.platform-mq-prod.svc
        port: 9092
        auto_commit: True
        timeout_ms: 1000
      inspectPendingImagesMinAge: 43200
      inspectPendingImagesSchedule: 900
  - name: scaligrade
    values:
      name: s
      scaligrade:
        enableImageChangeTrigger: true
        imageStreamName: s
        imageStreamTag: latest
        limits:
          container:
            cpuRequest: 100m
            cpuLimit: 100m
            memRequest: 64Mi
            memLimit: 128Mi
        port: 8080
        replicaCount: 1
        replicaCountMax: 3
        targetAverageCPUUtilization: 70
        sentry:
          enabled: false
