---
global:
  env: prod
  namespace: cloudigrade-prod
  fancyDomain: true
  fancyDomainTLS: true
  tls: true
include:
  - name: cloudigrade
    values:
      name: c1
      healthCheckHostHeader: health.cloudigrade.insights.openshiftapps.com
      api:
        enableImageChangeTrigger: true
        imageStreamName: c1
        imageStreamTag: latest
        limits:
          container:
            cpuRequest: 100m
            cpuLimit: 200m
            memRequest: 256Mi
            memLimit: 512Mi
        fancyRouteHost: www.cloudigra.de
        replicaCount: 2
        replicaCountMax: 8
        routeHost:
        routePath: /api/v1/
        sentry:
          enabled: true
        targetAverageCPUUtilization: 80
      auth:
        fancyRouteHost: www.cloudigra.de
        routeHost:
        routePath: /auth/
      nginx:
        enableImageChangeTrigger: true
        imageStreamName: c1-nginx
        imageStreamTag: latest
        limits:
          container:
            cpuRequest: 100m
            cpuLimit: 100m
            memRequest: 64Mi
            memLimit: 128Mi
        port: 8080
      celery:
        enableImageChangeTrigger: true
        imageStreamName: c1
        imageStreamTag: latest
        limits:
          container:
            cpuRequest: 300m
            cpuLimit: 500m
            memRequest: 512Mi
            memLimit: 1Gi
        beat:
          replicaCount: 1
          limits:
            container:
              cpuRequest: 100m
              cpuLimit: 100m
              memRequest: 64Mi
              memLimit: 128Mi
        sentry:
          enabled: true
        worker:
          replicaCount: 3
          replicaCountMax: 8
          targetAverageCPUUtilization: 80
          limits:
            container:
              cpuRequest: 100m
              cpuLimit: 200m
              memRequest: 256Mi
              memLimit: 512Mi
      aws:
        sqs:
          defaultRegion: us-east-1
          accessKeyId:
          secretAccessKey:
          namePrefix: prod-
          maxReceiveCount: 5
        defaultRegion: us-east-1
        accessKeyId:
        secretAccessKey:
        houndigrade:
          ecs:
            clusterName: cloudigrade-pilot-prod-us-east-1c
            imageName: registry.gitlab.com/cloudigrade/houndigrade
            imageTag: 0.1.4
            familyName: Houndigrade
          availabilityZone: us-east-1c
          autoscalingGroupName: EC2ContainerService-cloudigrade-pilot-prod-us-east-1c-EcsInstanceAsg-1TFDXJ62MAITS
          scaleUpClusterSchedule: 3600
          persistInspectionResultsSchedule: 300
          sentry:
            enabled: true
        cloudtrailEventUrl:
        repopulateEc2InstanceMappingSchedule: 604800
        s3BucketName: prod-cloudigrade
        s3Lifecycle:
          name: s3_lifecycle_policy
          iaTransition: 30
          glacierTransition: 60
          maxAge: 1460
      django:
        debug: false
        allowedHosts: '*'
        settingsModule: config.settings.prod
        secretKey:
      db:
        secretsFileName:
        databaseHost:
        databaseName:
        databasePort: 5432
        databaseUser:
        databasePassword:
      inspectPendingImagesMinAge: 43200
      inspectPendingImagesSchedule: 900
  - name: frontigrade
    values:
      name: f
      frontigrade:
        enableImageChangeTrigger: true
        imageStreamName: f
        imageStreamTag: latest
        limits:
          container:
            cpuRequest: 100m
            cpuLimit: 100m
            memRequest: 64Mi
            memLimit: 128Mi
        port: 8080
        fancyRouteHost: www.cloudigra.de
        replicaCount: 2
        replicaCountMax: 6
        targetAverageCPUUtilization: 80
        routeHost:
        routePath: /
        sentry:
          enabled: false
  - name: scaligrade
    values:
      name: s
      scaligrade:
        enableImageChangeTrigger: true
        imageStreamName: s
        imageStreamTag: latest
        limits:
          container:
            cpuRequest: 100m
            cpuLimit: 100m
            memRequest: 64Mi
            memLimit: 128Mi
        port: 8080
        replicaCount: 1
        replicaCountMax: 3
        targetAverageCPUUtilization: 70
        sentry:
          enabled: false
