---
global:
  env: prod
  namespace: cloudigrade-prod
  fancyDomain: true
  fancyDomainTLS: true
  tls: true
include:
  - name: cloudigrade
    values:
      name: cloudigrade
      healthCheckHostHeader: health.cloudigrade.insights.openshiftapps.com
      api:
        enableImageChangeTrigger: true
        imageStreamName: cloudigrade
        imageStreamTag: latest
        limits:
          container:
            cpuRequest: 100m
            cpuLimit: 200m
            memRequest: 256Mi
            memLimit: 512Mi
        fancyRouteHost: www.cloudigra.de
        replicaCount: 2
        replicaCountMax: 8
        routeHost:
        routePath: /api/v1/
        sentry:
          enabled: true
        targetAverageCPUUtilization: 80
      auth:
        fancyRouteHost: www.cloudigra.de
        routeHost:
        routePath: /auth/
      nginx:
        enableImageChangeTrigger: true
        imageStreamName: cloudigrade-nginx
        imageStreamTag: latest
        limits:
          container:
            cpuRequest: 100m
            cpuLimit: 100m
            memRequest: 64Mi
            memLimit: 128Mi
        port: 8080
      celery:
        enableImageChangeTrigger: true
        imageStreamName: cloudigrade
        imageStreamTag: latest
        limits:
          container:
            cpuRequest: 300m
            cpuLimit: 500m
            memRequest: 512Mi
            memLimit: 1Gi
        beat:
          replicaCount: 1
          limits:
            container:
              cpuRequest: 100m
              cpuLimit: 100m
              memRequest: 64Mi
              memLimit: 128Mi
        sentry:
          enabled: true
        worker:
          replicaCount: 3
          replicaCountMax: 8
          targetAverageCPUUtilization: 80
          limits:
            container:
              cpuRequest: 100m
              cpuLimit: 200m
              memRequest: 256Mi
              memLimit: 512Mi
      aws:
        sqs:
          defaultRegion: us-east-1
          accessKeyId:
          secretAccessKey:
          namePrefix: prod-
        defaultRegion: us-east-1
        accessKeyId:
        secretAccessKey:
        houndigrade:
          ecs:
            clusterName: cloudigrade-prod-us-east-1c
            imageName: registry.gitlab.com/cloudigrade/houndigrade
            imageTag: 0.1.2
            familyName: Houndigrade
          availabilityZone: us-east-1c
          autoscalingGroupName: EC2ContainerService-cloudigrade-prod-us-east-1c-EcsInstanceAsg-UZR9Y10ZTWKM
          scaleUpClusterSchedule: 3600
          persistInspectionResultsSchedule: 300
          sentry:
            enabled: true
        cloudtrailEventUrl:
        s3BucketName: prod-cloudigrade
      django:
        debug: false
        allowedHosts: '*'
        settingsModule: config.settings.prod
        secretKey:
      db:
        secretsFileName:
        databaseHost:
        databaseName:
        databasePort: 5432
        databaseUser:
        databasePassword:
  - name: frontigrade
    values:
      name: frontigrade
      frontigrade:
        enableImageChangeTrigger: true
        imageStreamName: frontigrade
        imageStreamTag: latest
        limits:
          container:
            cpuRequest: 100m
            cpuLimit: 100m
            memRequest: 64Mi
            memLimit: 128Mi
        port: 8080
        fancyRouteHost: www.cloudigra.de
        replicaCount: 2
        replicaCountMax: 6
        targetAverageCPUUtilization: 80
        routeHost:
        routePath: /
        sentry:
          enabled: false
