{{/* We only use buildconfigs if the environment is local, or review. */}}
{{if or (eq .env "local") (eq .env "review")}}

{{/* Variables */}}
{{$prefix := or (env "DEPLOYMENT_PREFIX" | trunc 36) ""}}
{{$prefix := and $prefix (printf "-%s" $prefix)}}
{{$name := printf "%s%s" .name $prefix}}
{{$commit_ref_slug := env "CI_COMMIT_REF_SLUG"}}
{{$gitlab_deployment := env "GITLAB_DEPLOYMENT"}}

{{$sclaligrade_repo_uri := ((env "SCALIGRADE_REPO_URI") | default .scaligrade.repoUri)}}
{{$scaligrade_repo_ref := ((env "SCALIGRADE_REPO_REF") | default .scaligrade.repoUriBranch)}}

{{$scaligrade_imagestream_name := printf "%s%s" .scaligrade.imageStreamName $prefix}}
{{$scaligrade_imagestream_tag := .scaligrade.imageStreamTag}}

{{$scaligrade_limits_build_cpu_request := .scaligrade.limits.build.cpuRequest}}
{{$scaligrade_limits_build_mem_request := .scaligrade.limits.build.memRequest}}
{{$scaligrade_limits_build_cpu_limit := .scaligrade.limits.build.cpuLimit}}
{{$scaligrade_limits_build_mem_limit := .scaligrade.limits.build.memLimit}}

{{$not_local := ne .env "local"}}
{{$not_review := ne .env "review"}}
---
kind: BuildConfig
apiVersion: v1
metadata:
  name: {{$name}}
  labels:
{{if $commit_ref_slug}}
    app: {{$commit_ref_slug}}
{{end}}
    deployment: {{$name}}-deployment
{{if $gitlab_deployment}}
    gitlab-deployment: {{$gitlab_deployment}}
{{end}}
spec:
  failedBuildsHistoryLimit: 5
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: {{$sclaligrade_repo_uri}}
      ref: {{$scaligrade_repo_ref}}
  output:
    to:
      kind: ImageStreamTag
      name: {{$scaligrade_imagestream_name}}:{{$scaligrade_imagestream_tag}}
  strategy:
    type: Docker
  triggers:
{{if $not_review}}
  - type: ConfigChange
{{end}}
  - imageChange: {}
    type: ImageChange
{{if $not_local}}
{{/* Resource limits are only relevant when we're running in OSD */}}
  resources:
    requests:
      cpu: {{$scaligrade_limits_build_cpu_request}}
      memory: {{$scaligrade_limits_build_mem_request}}
    limits:
      cpu: {{$scaligrade_limits_build_cpu_limit}}
      memory: {{$scaligrade_limits_build_mem_limit}}
{{end}}
{{end}}
