---
# Check pre-requisites
- include: pre-requisites.yaml

- name: Purge messages from queues
  script: "clean-queues.py --prefix {{ aws_prefix }}"
  when: sqs_state == "clean"

- name: Delete sqs queues
  script: "clean-queues.py --prefix {{ aws_prefix }} --delete"
  when: sqs_state == "absent"
