{{$prefix := or (env "DEPLOYMENT_PREFIX") ""}}
{{if (eq .env "local") or (eq .env "review")}}
{{/* We only use buildconfigs if the environment is local, or review. */}}
---
kind: BuildConfig
apiVersion: v1
metadata:
  name: {{$prefix}}{{.name}}-nginx
  labels:
    deployment: {{$prefix}}{{.name}}-deployment
{{if (env "GITLAB_DEPLOYMENT")}}
    gitlab-deployment: {{env "GITLAB_DEPLOYMENT"}}
{{end}}
spec:
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: {{$prefix}}{{.nginx.imageStreamName}}:{{.nginx.imageStreamTag}}
  runPolicy: Serial
  source:
    contextDir: {{.nginx.repoContextDir}}
    git:
      uri: {{env "NGINX_REPO_URI" | default .nginx.repoUri}}
      ref: {{env "NGINX_REPO_REF" | default .nginx.repoUriBranch}}
    type: Git
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: {{.nginx.baseImage}}
  triggers:
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
{{if ne .env "local"}}
{{/* Resource limits are only relevant when we're running in OSD */}}
  resources:
    limits:
      cpu: {{env "CLOUDIGRADE_BC_CPU_LIMIT" | default .build.cpuLimit}}
      memory: {{env "CLOUDIGRADE_BC_MEM_LIMIT | default .build.memLimit"}}
{{end}}
---
kind: BuildConfig
apiVersion: v1
metadata:
  name: {{$prefix}}{{.name}}-api
  labels:
    deployment: {{$prefix}}{{.name}}-deployment
{{if (env "GITLAB_DEPLOYMENT")}}
    gitlab-deployment: {{env "GITLAB_DEPLOYMENT"}}
{{end}}
spec:
  failedBuildsHistoryLimit: 5
  runPolicy: Serial
  strategy:
    type: Docker
  source:
    type: Git
    git:
      uri: {{env "API_REPO_URI" | default .api.repoUri}}
      ref: {{env "API_REPO_REF" | default .api.repoUriBranch}}
  output:
    to:
      kind: ImageStreamTag
      name: {{$prefix}}{{.api.imageStreamName}}:{{.api.imageStreamTag}}
  triggers:
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
{{if ne .env "local"}}
  resources:
    limits:
      cpu: {{env "CLOUDIGRADE_BC_CPU_LIMIT" | default .build.cpuLimit}}
      memory: {{env "CLOUDIGRADE_BC_MEM_LIMIT | default .build.memLimit"}}
{{end}}
{{end}}
