{{/* Variables */}}
{{$prefix := or (env "DEPLOYMENT_PREFIX" | trunc 36) ""}}
{{$prefix := and $prefix (printf "-%s" $prefix)}}
{{$bucketprefix := or (env "DEPLOYMENT_PREFIX") (env "USER")}}
{{$name := printf "%s%s" .name $prefix}}
{{$commit_ref_slug := env "CI_COMMIT_REF_SLUG"}}
{{$gitlab_deployment := env "GITLAB_DEPLOYMENT"}}

{{$not_local := ne .env "local"}}
{{$not_local_or_review := and (ne .env "local") (ne .env "review")}}

{{$aws_default_region := .aws.defaultRegion}}

{{$aws_houndigrade_ecs_cluster_name := (env "HOUNDIGRADE_ECS_CLUSTER_NAME" | default .aws.houndigrade.ecs.clusterName)}}
{{$aws_houndigrade_ecs_image_name := (env "HOUNDIGRADE_ECS_IMAGE_NAME" | default .aws.houndigrade.ecs.imageName)}}
{{$aws_houndigrade_ecs_image_tag := (env "HOUNDIGRADE_ECS_IMAGE_TAG" | default .aws.houndigrade.ecs.imageTag | quote)}}
{{$aws_houndigrade_ecs_family_name := (env "HOUNDIGRADE_ECS_FAMILY_NAME" | default .aws.houndigrade.ecs.familyName)}}
{{$aws_houndigrade_ecs_availability_zone := (env "HOUNDIGRADE_AWS_AVAILABILITY_ZONE" | default .aws.houndigrade.availabilityZone)}}
{{$aws_houndigrade_ecs_autoscaling_group_name := (env "HOUNDIGRADE_AWS_AUTOSCALING_GROUP_NAME" | default .aws.houndigrade.autoscalingGroupName)}}
{{$aws_houndigrade_ecs_scale_up_cluster_schedule := (env "SCALE_UP_INSPECTION_CLUSTER_SCHEDULE" | default .aws.houndigrade.scaleUpClusterSchedule | quote)}}
{{$aws_houndigrade_ecs_persist_inspection_results_schedule := (env "PERSIST_INSPECTION_CLUSTER_RESULTS_SCHEDULE" | default .aws.houndigrade.persistInspectionResultsSchedule | quote)}}

{{$aws_repopulate_ec2_instance_mapping_schedule := (env "REPOPULATE_EC2_INSTANCE_MAPPING_SCHEDULE" | default .aws.repopulateEc2InstanceMappingSchedule | quote)}}

{{$aws_sqs_default_region := .aws.sqs.defaultRegion}}
{{$aws_cloudtrail_event_url := (env "CLOUDTRAIL_EVENT_URL" | default .aws.cloudtrailEventUrl)}}
{{$aws_sqs_max_receive_count := (env "AWS_SQS_MAX_RECEIVE_COUNT" | default .aws.sqs.maxReceiveCount | quote)}}

{{$aws_sqs_name_prefix := .aws.sqs.namePrefix | quote}}
{{$aws_not_local_name_prefix := (or (env "DEPLOYMENT_PREFIX") ($aws_sqs_name_prefix))}}
{{$aws_not_local_bucket_name := (env "AWS_S3_BUCKET_NAME" | default .aws.s3BucketName)}}
{{$aws_local_name_prefix := (or (env "DEPLOYMENT_PREFIX") (env "USER" | printf "%s-")) | quote}}
{{$aws_local_bucketprefix_name := ($bucketprefix | printf "%s-cloudigrade-s3" | quote)}}
{{$aws_local_bucket_name := (or (env "AWS_S3_BUCKET_NAME") ($aws_local_bucketprefix_name))}}

{{$django_allowed_hosts := .django.allowedHosts | quote}}
{{$django_database_host := env "DJANGO_DATABASE_HOST" | default .db.databaseHost}}
{{$django_debug := .django.debug | quote}}
{{$django_settings_module := .django.settingsModule}}

{{$database_name := (env "DJANGO_DATABASE_NAME" | default .db.databaseName)}}
{{$database_port := (env "DJANGO_DATABASE_PORT" | default .db.databasePort | quote)}}

{{$api_sentry_enabled := (or (env "API_SENTRY_ENABLED") (.api.sentry.enabled))}}
{{$api_sentry_enabled_str := $api_sentry_enabled | quote}}
{{$api_sentry_environment := env "API_SENTRY_ENVIRONMENT"}}
{{$api_sentry_release := env "API_SENTRY_RELEASE"}}

{{$celery_sentry_enabled := (or (env "CELERY_SENTRY_ENABLED") (.celery.sentry.enabled))}}
{{$celery_sentry_enabled_str := $celery_sentry_enabled | quote}}
{{$celery_sentry_environment := env "CELERY_SENTRY_ENVIRONMENT"}}
{{$celery_sentry_release := env "CELERY_SENTRY_RELEASE"}}

{{$houndigrade_sentry_enabled := (or (env "HOUNDIGRADE_SENTRY_ENABLED") (.aws.houndigrade.sentry.enabled))}}
{{$houndigrade_sentry_enabled_str := $houndigrade_sentry_enabled | quote}}
{{$houndigrade_sentry_environment := env "HOUNDIGRADE_SENTRY_ENVIRONMENT"}}

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{$name}}
  labels:
{{if $commit_ref_slug}}
    app: {{$commit_ref_slug}}
{{end}}
    deployment: {{$name}}-deployment
{{if $gitlab_deployment}}
    gitlab-deployment: {{$gitlab_deployment}}
{{end}}
data:
  aws-default-region: {{$aws_default_region}}
  aws-houndigrade-ecs-cluster-name: {{$aws_houndigrade_ecs_cluster_name}}
  aws-houndigrade-ecs-image-name: {{$aws_houndigrade_ecs_image_name}}
  aws-houndigrade-ecs-image-tag: {{$aws_houndigrade_ecs_image_tag}}
  aws-houndigrade-ecs-family-name: {{$aws_houndigrade_ecs_family_name}}
  aws-houndigrade-availability-zone: {{$aws_houndigrade_ecs_availability_zone}}
  aws-houndigrade-autoscaling-group-name: {{$aws_houndigrade_ecs_autoscaling_group_name}}
  aws-houndigrade-scale-up-cluster-schedule: {{$aws_houndigrade_ecs_scale_up_cluster_schedule}}
  aws-houndigrade-persist-inspection-results-schedule: {{$aws_houndigrade_ecs_persist_inspection_results_schedule}}
  aws-repopulate-ec2-instance-mapping-schedule: {{$aws_repopulate_ec2_instance_mapping_schedule}}
  aws-sqs-region: {{$aws_sqs_default_region}}
  aws-cloudtrail-event-url: {{$aws_cloudtrail_event_url}}
  aws-sqs-max-receive-count: {{$aws_sqs_max_receive_count}}
{{if $not_local}}
  aws-name-prefix: {{$aws_not_local_name_prefix}}
  aws-s3-bucket-name: {{$aws_not_local_bucket_name}}
{{else}}
  aws-name-prefix: {{$aws_local_name_prefix}}
  aws-s3-bucket-name: {{$aws_local_bucket_name}}
{{end}}
  django-allowed-hosts: {{$django_allowed_hosts}}
  django-database-host: {{$django_database_host}}
  django-debug: {{$django_debug}}
  django-settings-module: {{$django_settings_module}}
{{if $not_local_or_review}}
  database-name: {{$database_name}}
  database-port: {{$database_port}}
{{end}}
{{if $api_sentry_enabled}}
  api-sentry-enabled: {{$api_sentry_enabled_str}}
  api-sentry-environment: {{$api_sentry_environment}}
  api-sentry-release: {{$api_sentry_release}}
{{end}}
{{if $celery_sentry_enabled}}
  celery-sentry-enabled: {{$celery_sentry_enabled_str}}
  celery-sentry-environment: {{$celery_sentry_environment}}
  celery-sentry-release: {{$celery_sentry_release}}
{{end}}
{{if $houndigrade_sentry_enabled}}
  houndigrade-sentry-enabled: {{$houndigrade_sentry_enabled_str}}
  houndigrade-sentry-environment: {{$houndigrade_sentry_environment}}
{{end}}
type: Opaque
