---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{.name}}
  labels:
    deployment: {{.name}}-deployment
data:
  aws-default-region: {{.aws.defaultRegion}}
  aws-houndigrade-ecs-cluster-name: {{env "HOUNDIGRADE_ECS_CLUSTER_NAME" | default .aws.houndigrade.ecs.clusterName}}
  aws-houndigrade-ecs-image-name: {{env "HOUNDIGRADE_ECS_IMAGE_NAME" | default .aws.houndigrade.ecs.imageName}}
  aws-houndigrade-ecs-family-name: {{env "HOUNDIGRADE_ECS_FAMILY_NAME" | default .aws.houndigrade.ecs.familyName}}
  aws-houndigrade-availability-zone: {{env "HOUNDIGRADE_AWS_AVAILABILITY_ZONE" | default .aws.houndigrade.availabilityZone}}
  aws-houndigrade-autoscaling-group-name: {{env "HOUNDIGRADE_AWS_AUTOSCALING_GROUP_NAME" | default .aws.houndigrade.autoscalingGroupName}}
  aws-houndigrade-scale-up-cluster-schedule: {{env "SCALE_UP_INSPECTION_CLUSTER_SCHEDULE" | default .aws.houndigrade.scaleUpClusterSchedule | toString}}
  aws-sqs-region: {{.aws.sqs.defaultRegion}}
{{if ne .env "local"}}
  aws-sqs-queue-name-prefix: {{.aws.sqs.namePrefix}}
{{else}}
  aws-sqs-queue-name-prefix: {{env "USER" | printf "%s-" | quote}}
{{end}}
  django-allowed-hosts: {{.django.allowedHosts | quote}}
  django-database-host: {{.db.databaseHost}}
  django-debug: {{.django.debug | quote}}
  django-settings-module: {{.django.settingsModule}}
type: Opaque
