{{$prefix := or (env "DEPLOYMENT_PREFIX") ""}}
{{$bucketprefix := or (env "DEPLOYMENT_PREFIX") (env "USER")}}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{$prefix}}{{.name}}
  labels:
    deployment: {{$prefix}}{{.name}}-deployment
{{if (env "GITLAB_DEPLOYMENT")}}
    gitlab-deployment: {{env "GITLAB_DEPLOYMENT"}}
{{end}}
data:
  aws-default-region: {{.aws.defaultRegion}}
  aws-houndigrade-ecs-cluster-name: {{env "HOUNDIGRADE_ECS_CLUSTER_NAME" | default .aws.houndigrade.ecs.clusterName}}
  aws-houndigrade-ecs-image-name: {{env "HOUNDIGRADE_ECS_IMAGE_NAME" | default .aws.houndigrade.ecs.imageName}}
  aws-houndigrade-ecs-image-tag: {{env "HOUNDIGRADE_ECS_IMAGE_TAG" | default .aws.houndigrade.ecs.imageTag | quote}}
  aws-houndigrade-ecs-family-name: {{env "HOUNDIGRADE_ECS_FAMILY_NAME" | default .aws.houndigrade.ecs.familyName}}
  aws-houndigrade-availability-zone: {{env "HOUNDIGRADE_AWS_AVAILABILITY_ZONE" | default .aws.houndigrade.availabilityZone}}
  aws-houndigrade-autoscaling-group-name: {{env "HOUNDIGRADE_AWS_AUTOSCALING_GROUP_NAME" | default .aws.houndigrade.autoscalingGroupName}}
  aws-houndigrade-scale-up-cluster-schedule: {{env "SCALE_UP_INSPECTION_CLUSTER_SCHEDULE" | default .aws.houndigrade.scaleUpClusterSchedule | quote}}
  aws-houndigrade-persist-inspection-results-schedule: {{env "PERSIST_INSPECTION_CLUSTER_RESULTS_SCHEDULE" | default .aws.houndigrade.persistInspectionResultsSchedule | quote}}
  aws-sqs-region: {{.aws.sqs.defaultRegion}}
  aws-cloudtrail-event-url: {{env "CLOUDTRAIL_EVENT_URL" | default .aws.cloudtrailEventUrl}}
{{if ne .env "local"}}
  aws-name-prefix: {{if (env "DEPLOYMENT_PREFIX")}}{{env "DEPLOYMENT_PREFIX" | quote}}{{else}}{{.aws.sqs.namePrefix}}{{end}}
  aws-s3-bucket-name: {{env "AWS_S3_BUCKET_NAME" | default .aws.s3BucketName}}
{{else}}
  aws-name-prefix: {{if (env "DEPLOYMENT_PREFIX")}}{{env "DEPLOYMENT_PREFIX" | quote}}{{else}}{{ env "USER" | printf "%s-" | quote}}{{end}}
  aws-s3-bucket-name: {{if (env "AWS_S3_BUCKET_NAME")}}{{env "AWS_S3_BUCKET_NAME"}}{{else}}{{ $bucketprefix | printf "%s-cloudigrade-s3" | quote}}{{end}}
{{end}}
  django-allowed-hosts: {{.django.allowedHosts | quote}}
  django-database-host: {{env "DJANGO_DATABASE_HOST" | default .db.databaseHost}}
  django-debug: {{.django.debug | quote}}
  django-settings-module: {{.django.settingsModule}}
{{if and (ne .env "local") (ne .env "review")}}
  database-name: {{env "DJANGO_DATABASE_NAME" | default .db.databaseName}}
  database-port: {{env "DJANGO_DATABASE_PORT" | default .db.databasePort | quote}}
{{end}}
{{if or (env "API_SENTRY_ENABLED") (.api.sentry.enabled)}}
  api-sentry-enabled: {{env "API_SENTRY_ENABLED" | default .api.sentry.enabled}}
  api-sentry-environment: {{env "API_SENTRY_ENVIRONMENT"}}
  api-sentry-release: {{env "API_SENTRY_RELEASE"}}
{{end}}
{{if or (env "CELERY_SENTRY_ENABLED") (.celery.sentry.enabled)}}
  celery-sentry-enabled: {{env "CELERY_SENTRY_ENABLED" | default .celery.sentry.enabled}}
  celery-sentry-environment: {{env "CELERY_SENTRY_ENVIRONMENT"}}
  celery-sentry-release: {{env "CELERY_SENTRY_RELEASE"}}
{{end}}
{{if or (env "HOUNDIGRADE_SENTRY_ENABLED") (.aws.houndigrade.sentry.enabled)}}
  houndigrade-sentry-enabled: {{env "HOUNDIGRADE_SENTRY_ENABLED" | default .aws.houndigrade.sentry.enabled}}
  houndigrade-sentry-environment: {{env "HOUNDIGRADE_SENTRY_ENVIRONMENT"}}
{{end}}
type: Opaque
