---
kind: DeploymentConfig
apiVersion: v1
metadata:
  name: {{.name}}-api
  labels:
    deployment: {{.name}}-deployment
{{if (env "GITLAB_DEPLOYMENT")}}
    gitlab-deployment: {{env "GITLAB_DEPLOYMENT"}}
{{end}}
spec:
  selector:
    name: {{.name}}-api
  replicas: 1
  revisionHistoryLimit: 10
  strategy:
    recreateParams:
      mid:
        execNewPod:
          command:
          - scl
          - enable
          - rh-postgresql96
          - rh-python36
          - ./manage.py migrate
          containerName: {{.name}}-api
        failurePolicy: Abort
    type: Recreate
  template:
    metadata:
      labels:
        name: {{.name}}-api
    spec:
      containers:
      - name: {{.name}}-api
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: aws-access-key-id
              name: {{.name}}
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: aws-secret-access-key
              name: {{.name}}
        - name: AWS_DEFAULT_REGION
          valueFrom:
            configMapKeyRef:
              key: aws-default-region
              name: {{.name}}
        - name: AWS_SQS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: aws-sqs-access-key-id
              name: {{.name}}
        - name: AWS_SQS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: aws-sqs-secret-access-key
              name: {{.name}}
        - name: AWS_SQS_REGION
          valueFrom:
            configMapKeyRef:
              key: aws-sqs-region
              name: {{.name}}
        - name: AWS_NAME_PREFIX
          valueFrom:
            configMapKeyRef:
              key: aws-name-prefix
              name: {{.name}}
        - name: DJANGO_SETTINGS_MODULE
          valueFrom:
            configMapKeyRef:
              key: django-settings-module
              name: {{.name}}
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: django-secret-key
              name: {{.name}}
        - name: DJANGO_ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              key: django-allowed-hosts
              name: {{.name}}
        - name: DJANGO_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              key: database-name
              name: {{.db.secretsFileName}}
        - name: DJANGO_DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              key: django-database-host
              name: {{.name}}
        - name: DJANGO_DATABASE_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: {{.db.secretsFileName}}
        - name: DJANGO_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: {{.db.secretsFileName}}
        - name: DJANGO_DEBUG
          valueFrom:
            configMapKeyRef:
              key: django-debug
              name: {{.name}}
        - name: HOUNDIGRADE_ECS_CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              key: aws-houndigrade-ecs-cluster-name
              name: {{.name}}
        - name: HOUNDIGRADE_ECS_IMAGE_NAME
          valueFrom:
            configMapKeyRef:
              key: aws-houndigrade-ecs-image-name
              name: {{.name}}
        - name: HOUNDIGRADE_ECS_FAMILY_NAME
          valueFrom:
            configMapKeyRef:
              key: aws-houndigrade-ecs-family-name
              name: {{.name}}
        - name: HOUNDIGRADE_AWS_AVAILABILITY_ZONE
          valueFrom:
            configMapKeyRef:
              key: aws-houndigrade-availability-zone
              name: {{.name}}
        - name: HOUNDIGRADE_AWS_AUTOSCALING_GROUP_NAME
          valueFrom:
            configMapKeyRef:
              key: aws-houndigrade-autoscaling-group-name
              name: {{.name}}
        - name: CLOUDTRAIL_EVENT_URL
          valueFrom:
            configMapKeyRef:
              key: aws-cloudtrail-event-url
              name: {{.name}}
        image: ' '
        imagePullPolicy: Always
        resources:
          limits:
            memory: {{.api.memoryLimit}}
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - 'ps axo command | grep -v grep | grep gunicorn'
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - 'nc -U /var/run/cloudigrade/gunicorn.sock --send-only </dev/null'
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /var/run/cloudigrade
          name: {{.name}}-socket
      - name: nginx
        image: ' '
        imagePullPolicy: Always
        ports:
        - containerPort: {{.nginx.port}}
          protocol: TCP
        resources:
          limits:
            memory: {{.nginx.memoryLimit}}
        livenessProbe:
          tcpSocket:
            port: {{.nginx.port}}
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz/
            port: {{.nginx.port}}
            scheme: HTTP
            httpHeaders:
              - name: Host
                value: {{.healthCheckHostHeader}}
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /var/run/cloudigrade
          name: {{.name}}-socket
      volumes:
      - name: {{.name}}-socket
        emptyDir: {}
  triggers:
    - type: "ImageChange"
      imageChangeParams:
        automatic: {{.api.enableImageChangeTrigger}}
        containerNames:
          - {{.name}}-api
        from:
          kind: ImageStreamTag
          name: {{.api.imageStreamName}}:{{.api.imageStreamTag}}
    - type: ImageChange
      imageChangeParams:
        automatic: {{.nginx.enableImageChangeTrigger}}
        containerNames:
          - nginx
        from:
          kind: ImageStreamTag
          name: {{.nginx.imageStreamName}}:{{.nginx.imageStreamTag}}
    - type: ConfigChange
---
kind: DeploymentConfig
apiVersion: v1
metadata:
  name: {{.name}}-celery
  labels:
    deployment: {{.name}}-deployment
{{if (env "GITLAB_DEPLOYMENT")}}
    gitlab-deployment: {{env "GITLAB_DEPLOYMENT"}}
{{end}}
spec:
spec:
  selector:
    name: {{.name}}-celery
  replicas: {{.celery.replicaCount}}
  revisionHistoryLimit: 10
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{.name}}-celery
    spec:
      containers:
      - name: {{.name}}-celery
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: aws-access-key-id
              name: {{.name}}
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: aws-secret-access-key
              name: {{.name}}
        - name: AWS_DEFAULT_REGION
          valueFrom:
            configMapKeyRef:
              key: aws-default-region
              name: {{.name}}
        - name: AWS_SQS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              key: aws-sqs-access-key-id
              name: {{.name}}
        - name: AWS_SQS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: aws-sqs-secret-access-key
              name: {{.name}}
        - name: AWS_SQS_REGION
          valueFrom:
            configMapKeyRef:
              key: aws-sqs-region
              name: {{.name}}
        - name: AWS_NAME_PREFIX
          valueFrom:
            configMapKeyRef:
              key: aws-name-prefix
              name: {{.name}}
        - name: DJANGO_SETTINGS_MODULE
          valueFrom:
            configMapKeyRef:
              key: django-settings-module
              name: {{.name}}
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: django-secret-key
              name: {{.name}}
        - name: DJANGO_ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              key: django-allowed-hosts
              name: {{.name}}
        - name: DJANGO_DATABASE_NAME
          valueFrom:
            secretKeyRef:
              key: database-name
              name: {{.db.secretsFileName}}
        - name: DJANGO_DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              key: django-database-host
              name: {{.name}}
        - name: DJANGO_DATABASE_USER
          valueFrom:
            secretKeyRef:
              key: database-user
              name: {{.db.secretsFileName}}
        - name: DJANGO_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: database-password
              name: {{.db.secretsFileName}}
        - name: DJANGO_DEBUG
          valueFrom:
            configMapKeyRef:
              key: django-debug
              name: {{.name}}
        - name: HOUNDIGRADE_ECS_CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              key: aws-houndigrade-ecs-cluster-name
              name: {{.name}}
        - name: HOUNDIGRADE_ECS_IMAGE_NAME
          valueFrom:
            configMapKeyRef:
              key: aws-houndigrade-ecs-image-name
              name: {{.name}}
        - name: HOUNDIGRADE_ECS_FAMILY_NAME
          valueFrom:
            configMapKeyRef:
              key: aws-houndigrade-ecs-family-name
              name: {{.name}}
        - name: HOUNDIGRADE_AWS_AVAILABILITY_ZONE
          valueFrom:
            configMapKeyRef:
              key: aws-houndigrade-availability-zone
              name: {{.name}}
        - name: HOUNDIGRADE_AWS_AUTOSCALING_GROUP_NAME
          valueFrom:
            configMapKeyRef:
              key: aws-houndigrade-autoscaling-group-name
              name: {{.name}}
        - name: SCALE_UP_INSPECTION_CLUSTER_SCHEDULE
          valueFrom:
            configMapKeyRef:
              key: aws-houndigrade-scale-up-cluster-schedule
              name: {{.name}}
        - name: CLOUDTRAIL_EVENT_URL
          valueFrom:
            configMapKeyRef:
              key: aws-cloudtrail-event-url
              name: {{.name}}
        image: ' '
        imagePullPolicy: Always
        command:
          - /bin/sh
          - -c
          - >
            PYTHONPATH=. scl enable rh-postgresql96 rh-python36 --
            celery -l info -A config worker --beat
            --scheduler django_celery_beat.schedulers:DatabaseScheduler
            -Q copy_ami_snapshot,copy_ami_to_customer_account,remove_snapshot_ownership,create_volume,delete_snapshot,enqueue_ready_volumes,scale_up_inspection_cluster,run_inspection_cluster,persist_inspection_cluster_results_task,scale_down_cluster,analyze_log
        resources:
          limits:
            memory: {{.celery.memoryLimit}}
        livenessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - 'ps axo command | grep -v grep | grep python'
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          exec:
            command:
              - /bin/sh
              - -c
              - '[[ $(ps axo command | grep "[p]ython" | grep celery | grep -c worker) -gt 1 ]]'
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
  triggers:
    - type: "ImageChange"
      imageChangeParams:
        automatic: {{.celery.enableImageChangeTrigger}}
        containerNames:
          - {{.name}}-celery
        from:
          kind: ImageStreamTag
          name: {{.celery.imageStreamName}}:{{.celery.imageStreamTag}}
    - type: ConfigChange
