{{if and (ne .env "local") (ne .env "review")}}
{{/* Variables */}}
{{$prefix := or (env "DEPLOYMENT_PREFIX" | trunc 36) ""}}
{{$prefix := and $prefix (printf "-%s" $prefix)}}
{{$name := printf "%s%s" .name $prefix}}
{{$commit_ref_slug := env "CI_COMMIT_REF_SLUG"}}
{{$gitlab_deployment := env "GITLAB_DEPLOYMENT"}}

{{$api_replicaCount := .api.replicaCount}}
{{$api_replicaCountMax := .api.replicaCountMax}}
{{$api_targetAverageCPUUtilization := .api.targetAverageCPUUtilization}}

{{$celery_replicaCount := .celery.worker.replicaCount}}
{{$celery_replicaCountMax := .celery.worker.replicaCountMax}}
{{$celery_targetAverageCPUUtilization := .celery.worker.targetAverageCPUUtilization}}

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{$name}}-a-cpu
  labels:
{{if $commit_ref_slug}}
    app: {{$commit_ref_slug}}
{{end}}
    deployment: {{$name}}-deployment
{{if $gitlab_deployment}}
    gitlab-deployment: {{$gitlab_deployment}}
{{end}}
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: DeploymentConfig
    name: {{$name}}-a
  minReplicas: {{$api_replicaCount}}
  maxReplicas: {{$api_replicaCountMax}}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{$api_targetAverageCPUUtilization}}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{$name}}-w-cpu
  labels:
{{if $commit_ref_slug}}
    app: {{$commit_ref_slug}}
{{end}}
    deployment: {{$name}}-deployment
{{if $gitlab_deployment}}
    gitlab-deployment: {{$gitlab_deployment}}
{{end}}
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: DeploymentConfig
    name: {{$name}}-w
  minReplicas: {{$celery_replicaCount}}
  maxReplicas: {{$celery_replicaCountMax}}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{$celery_targetAverageCPUUtilization}}
{{end}}
