---
kind: ImageStream
apiVersion: v1
metadata:
  name: {{.nginx.imageStreamName}}
  labels:
    deployment: {{.name}}-deployment
---
kind: ImageStream
apiVersion: v1
metadata:
  name: {{.api.imageStreamName}}
  labels:
    deployment: {{.name}}-deployment
