{{if or (eq .env "local") (eq .env "review")}}
{{$prefix := or (env "DEPLOYMENT_PREFIX") ""}}
---
kind: ImageStream
apiVersion: v1
metadata:
  name: {{$prefix}}{{.nginx.imageStreamName}}
  labels:
    deployment: {{$prefix}}{{.name}}-deployment
{{if (env "GITLAB_DEPLOYMENT")}}
    gitlab-deployment: {{env "GITLAB_DEPLOYMENT"}}
{{end}}
---
kind: ImageStream
apiVersion: v1
metadata:
  name: {{$prefix}}{{.api.imageStreamName}}
  labels:
    deployment: {{$prefix}}{{.name}}-deployment
{{if (env "GITLAB_DEPLOYMENT")}}
    gitlab-deployment: {{env "GITLAB_DEPLOYMENT"}}
{{end}}
{{end}}
