---
kind: ImageStream
apiVersion: v1
metadata:
  name: {{.nginx.imageStreamName}}
  labels:
    deployment: {{.name}}-deployment
{{if (env "GITLAB_DEPLOYMENT")}}
    gitlab-deployment: {{env "GITLAB_DEPLOYMENT"}}
{{end}}
---
kind: ImageStream
apiVersion: v1
metadata:
  name: {{.api.imageStreamName}}
  labels:
    deployment: {{.name}}-deployment
{{if (env "GITLAB_DEPLOYMENT")}}
    gitlab-deployment: {{env "GITLAB_DEPLOYMENT"}}
{{end}}
