---
kind: Route
apiVersion: v1
metadata:
  name: {{.name}}-api
  labels:
    deployment: {{.name}}-deployment
spec:
  host: {{env "API_ROUTE_HOST" | default .api.routeHost}}
  path: {{env "API_ROUTE_PATH" | default .api.routePath}}
  port:
    targetPort: nginx
  to:
    kind: Service
    name: {{.name}}-api
    weight: 100
  wildcardPolicy: None
---
kind: Route
apiVersion: v1
metadata:
  name: {{.name}}-auth
  labels:
    deployment: {{.name}}-deployment
spec:
  host: {{env "AUTH_ROUTE_HOST" | default .auth.routeHost}}
  path: {{env "AUTH_ROUTE_PATH" | default .auth.routePath}}
  port:
    targetPort: nginx
  to:
    kind: Service
    name: {{.name}}-api
    weight: 100
  wildcardPolicy: None
