{{/* Variables */}}
{{$prefix := or (env "DEPLOYMENT_PREFIX" | trunc 36) ""}}
{{$prefix := and $prefix (printf "-%s" $prefix)}}
{{$name := printf "%s%s" .name $prefix}}
{{$commit_ref_slug := env "CI_COMMIT_REF_SLUG"}}
{{$gitlab_deployment := env "GITLAB_DEPLOYMENT"}}

{{$api_route_host := (env "API_ROUTE_HOST" | default .api.routeHost)}}
{{$api_route_path := (env "API_ROUTE_PATH" | default .api.routePath)}}

{{$auth_route_host := (env "AUTH_ROUTE_HOST" | default .auth.routeHost)}}
{{$auth_route_path := (env "AUTH_ROUTE_PATH" | default .auth.routePath)}}

{{$api_target_port := printf "c%s-nginx" $prefix}}

{{$tls := .tls}}

{{$fancy_domain := .fancyDomain}}
{{$fancy_domain_tls := (.fancyDomainTLS | quote)}}
{{$api_fancy_route_host := (env "API_FANCY_ROUTE_HOST" | default .api.fancyRouteHost)}}
{{$auth_fancy_route_host := (env "AUTH_FANCY_ROUTE_HOST" | default .auth.fancyRouteHost)}}

---
kind: Route
apiVersion: v1
metadata:
  name: {{$name}}-api
  labels:
{{if $commit_ref_slug}}
    app: {{$commit_ref_slug}}
{{end}}
    deployment: {{$name}}-deployment
{{if $gitlab_deployment}}
    gitlab-deployment: {{$gitlab_deployment}}
{{end}}
spec:
{{if $api_route_host}}
  host: {{$api_route_host}}
{{end}}
  path: {{$api_route_path}}
  port:
    targetPort: {{$api_target_port}}
{{if $tls}}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
{{end}}
  to:
    kind: Service
    name: {{$name}}-api
    weight: 100
  wildcardPolicy: None
---
kind: Route
apiVersion: v1
metadata:
  name: {{$name}}-auth
  labels:
{{if $commit_ref_slug}}
    app: {{$commit_ref_slug}}
{{end}}
    deployment: {{$name}}-deployment
{{if $gitlab_deployment}}
    gitlab-deployment: {{$gitlab_deployment}}
{{end}}
spec:
{{if $auth_route_host}}
  host: {{$auth_route_host}}
{{end}}
  path: {{$auth_route_path}}
  port:
    targetPort: {{$api_target_port}}
{{if $tls}}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
{{end}}
  to:
    kind: Service
    name: {{$name}}-api
    weight: 100
  wildcardPolicy: None
{{if $fancy_domain}}
---
kind: Route
apiVersion: v1
metadata:
  name: {{$name}}-api-f
  annotations:
    kubernetes.io/tls-acme: {{$fancy_domain_tls}}
  labels:
{{if $commit_ref_slug}}
    app: {{$commit_ref_slug}}
{{end}}
    deployment: {{$name}}-deployment
{{if $gitlab_deployment}}
    gitlab-deployment: {{$gitlab_deployment}}
{{end}}
spec:
  host: {{$api_fancy_route_host}}
  path: {{$api_route_path}}
  port:
    targetPort: {{$api_target_port}}
  to:
    kind: Service
    name: {{$name}}-api
    weight: 100
  wildcardPolicy: None
---
kind: Route
apiVersion: v1
metadata:
  name: {{$name}}-auth-f
  annotations:
    kubernetes.io/tls-acme: {{$fancy_domain_tls}}
  labels:
{{if $commit_ref_slug}}
    app: {{$commit_ref_slug}}
{{end}}
    deployment: {{$name}}-deployment
{{if $gitlab_deployment}}
    gitlab-deployment: {{$gitlab_deployment}}
{{end}}
spec:
  host: {{$auth_fancy_route_host}}
  path: {{$auth_route_path}}
  port:
    targetPort: {{$api_target_port}}
  to:
    kind: Service
    name: {{$name}}-api
    weight: 100
  wildcardPolicy: None
{{end}}
