---
kind: Route
apiVersion: v1
metadata:
  name: {{if (env "DEPLOYMENT_PREFIX")}}{{env "DEPLOYMENT_PREFIX"}}-{{end}}{{.name}}-api
  labels:
    deployment: {{if (env "DEPLOYMENT_PREFIX")}}{{env "DEPLOYMENT_PREFIX"}}-{{end}}{{.name}}-deployment
{{if (env "GITLAB_DEPLOYMENT")}}
    gitlab-deployment: {{env "GITLAB_DEPLOYMENT"}}
{{end}}
spec:
  host: {{env "API_ROUTE_HOST" | default .api.routeHost}}
  path: {{env "API_ROUTE_PATH" | default .api.routePath}}
  port:
    targetPort: nginx
  to:
    kind: Service
    name: {{if (env "DEPLOYMENT_PREFIX")}}{{env "DEPLOYMENT_PREFIX"}}-{{end}}{{.name}}-api
    weight: 100
  wildcardPolicy: None
---
kind: Route
apiVersion: v1
metadata:
  name: {{if (env "DEPLOYMENT_PREFIX")}}{{env "DEPLOYMENT_PREFIX"}}-{{end}}{{.name}}-auth
  labels:
    deployment: {{if (env "DEPLOYMENT_PREFIX")}}{{env "DEPLOYMENT_PREFIX"}}-{{end}}{{.name}}-deployment
{{if (env "GITLAB_DEPLOYMENT")}}
    gitlab-deployment: {{env "GITLAB_DEPLOYMENT"}}
{{end}}
spec:
  host: {{env "AUTH_ROUTE_HOST" | default .auth.routeHost}}
  path: {{env "AUTH_ROUTE_PATH" | default .auth.routePath}}
  port:
    targetPort: nginx
  to:
    kind: Service
    name: {{if (env "DEPLOYMENT_PREFIX")}}{{env "DEPLOYMENT_PREFIX"}}-{{end}}{{.name}}-api
    weight: 100
  wildcardPolicy: None
