{{$prefix := or (env "DEPLOYMENT_PREFIX") ""}}
---
kind: Route
apiVersion: v1
metadata:
  name: {{$prefix}}{{.name}}-api
  labels:
{{if (env "CI_ENVIRONMENT_SLUG")}}
    app: {{env "CI_ENVIRONMENT_SLUG"}}
{{end}}
    deployment: {{$prefix}}{{.name}}-deployment
{{if (env "GITLAB_DEPLOYMENT")}}
    gitlab-deployment: {{env "GITLAB_DEPLOYMENT"}}
{{end}}
spec:
{{if or (env "API_ROUTE_HOST") (.api.routeHost)}}
  host: {{env "API_ROUTE_HOST" | default .api.routeHost}}
{{end}}
  path: {{env "API_ROUTE_PATH" | default .api.routePath}}
  port:
    targetPort: {{$prefix}}nginx
{{if .tls}}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
{{end}}
  to:
    kind: Service
    name: {{$prefix}}{{.name}}-api
    weight: 100
  wildcardPolicy: None
---
kind: Route
apiVersion: v1
metadata:
  name: {{$prefix}}{{.name}}-auth
  labels:
{{if (env "CI_ENVIRONMENT_SLUG")}}
    app: {{env "CI_ENVIRONMENT_SLUG"}}
{{end}}
    deployment: {{$prefix}}{{.name}}-deployment
{{if (env "GITLAB_DEPLOYMENT")}}
    gitlab-deployment: {{env "GITLAB_DEPLOYMENT"}}
{{end}}
spec:
{{if or (env "AUTH_ROUTE_HOST") (.auth.routeHost)}}
  host: {{env "AUTH_ROUTE_HOST" | default .auth.routeHost}}
{{end}}
  path: {{env "AUTH_ROUTE_PATH" | default .auth.routePath}}
  port:
    targetPort: {{$prefix}}nginx
{{if .tls}}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
{{end}}
  to:
    kind: Service
    name: {{$prefix}}{{.name}}-api
    weight: 100
  wildcardPolicy: None
{{if .fancyDomain}}
---
kind: Route
apiVersion: v1
metadata:
  name: {{$prefix}}{{.name}}-api-fancy
  annotations:
    kubernetes.io/tls-acme: {{.fancyDomainTLS | quote}}
  labels:
{{if (env "CI_ENVIRONMENT_SLUG")}}
    app: {{env "CI_ENVIRONMENT_SLUG"}}
{{end}}
    deployment: {{$prefix}}{{.name}}-deployment
{{if (env "GITLAB_DEPLOYMENT")}}
    gitlab-deployment: {{env "GITLAB_DEPLOYMENT"}}
{{end}}
spec:
  host: {{env "API_FANCY_ROUTE_PATH" | default .api.fancyRouteHost}}
  path: {{env "API_ROUTE_PATH" | default .api.routePath}}
  port:
    targetPort: {{$prefix}}nginx
  to:
    kind: Service
    name: {{$prefix}}{{.name}}-api
    weight: 100
  wildcardPolicy: None
---
kind: Route
apiVersion: v1
metadata:
  name: {{$prefix}}{{.name}}-auth-fancy
  annotations:
    kubernetes.io/tls-acme: {{.fancyDomainTLS | quote}}
  labels:
{{if (env "CI_ENVIRONMENT_SLUG")}}
    app: {{env "CI_ENVIRONMENT_SLUG"}}
{{end}}
    deployment: {{$prefix}}{{.name}}-deployment
{{if (env "GITLAB_DEPLOYMENT")}}
    gitlab-deployment: {{env "GITLAB_DEPLOYMENT"}}
{{end}}
spec:
  host: {{env "AUTH_FANCY_ROUTE_PATH" | default .auth.fancyRouteHost}}
  path: {{env "AUTH_ROUTE_PATH" | default .auth.routePath}}
  port:
    targetPort: {{$prefix}}nginx
  to:
    kind: Service
    name: {{$prefix}}{{.name}}-api
    weight: 100
  wildcardPolicy: None
{{end}}
