{{$prefix := or (env "DEPLOYMENT_PREFIX") ""}}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{$prefix}}{{.name}}
  labels:
    deployment: {{$prefix}}{{.name}}-deployment
{{if (env "GITLAB_DEPLOYMENT")}}
    gitlab-deployment: {{env "GITLAB_DEPLOYMENT"}}
{{end}}
data:
  aws-access-key-id: {{env "AWS_ACCESS_KEY_ID" | default .aws.accessKeyId | toString | b64enc}}
  aws-secret-access-key: {{env "AWS_SECRET_ACCESS_KEY" | default .aws.secretAccessKey | toString | b64enc}}
  django-secret-key: {{env "DJANGO_SECRET_KEY" | default .django.secretKey | toString | b64enc}}
  aws-sqs-access-key-id: {{env "AWS_SQS_ACCESS_KEY_ID" | default .aws.sqs.accessKeyId | toString | b64enc}}
  aws-sqs-secret-access-key: {{env "AWS_SQS_SECRET_ACCESS_KEY" | default .aws.sqs.secretAccessKey | toString | b64enc}}
{{if and (ne .env "local") (ne .env "review")}}
  database-user: {{env "DJANGO_DATABASE_USER" | default .db.databaseUser | toString | b64enc}}
  database-password: {{env "DJANGO_DATABASE_PASSWORD" | default .db.databasePassword | toString | b64enc}}
{{end}}
type: Opaque
