{{/* Variables */}}
{{$prefix := or (env "DEPLOYMENT_PREFIX" | trunc 36) ""}}
{{$prefix := and $prefix (printf "-%s" $prefix)}}
{{$name := printf "%s%s" .name $prefix}}
{{$commit_ref_slug := env "CI_COMMIT_REF_SLUG"}}
{{$gitlab_deployment := env "GITLAB_DEPLOYMENT"}}

{{$not_local_or_review := and (ne .env "local") (ne .env "review")}}

{{$aws_access_key_id := env "AWS_ACCESS_KEY_ID" | default .aws.accessKeyId | toString | b64enc}}
{{$aws_secret_access_key := env "AWS_SECRET_ACCESS_KEY" | default .aws.secretAccessKey | toString | b64enc}}

{{$aws_sqs_access_key_id := env "AWS_SQS_ACCESS_KEY_ID" | default .aws.sqs.accessKeyId | toString | b64enc}}
{{$aws_sqs_secret_access_key := env "AWS_SQS_SECRET_ACCESS_KEY" | default .aws.sqs.secretAccessKey | toString | b64enc}}

{{$django_secret_key := env "DJANGO_SECRET_KEY" | default .django.secretKey | toString | b64enc}}
{{$django_user := (or (env "DJANGO_DATABASE_USER" | default .db.databaseUser) " ") | toString | b64enc}}
{{$django_password := (or (env "DJANGO_DATABASE_PASSWORD" | default .db.databasePassword) " ") | toString | b64enc}}

{{$api_sentry_enabled := (or (env "API_SENTRY_ENABLED") (.api.sentry.enabled))}}
{{$api_sentry_dsn := env "API_SENTRY_DSN" | toString | b64enc}}

{{$celery_sentry_enabled := (or (env "CELERY_SENTRY_ENABLED") (.celery.sentry.enabled))}}
{{$celery_sentry_dsn := env "CELERY_SENTRY_DSN" | toString | b64enc}}

{{$houndigrade_sentry_enabled := (or (env "HOUNDIGRADE_SENTRY_ENABLED") (.aws.houndigrade.sentry.enabled))}}
{{$houndigrade_sentry_dsn := env "HOUNDIGRADE_SENTRY_DSN" | toString | b64enc}}

---
kind: Secret
apiVersion: v1
metadata:
  name: {{$name}}
  labels:
{{if $commit_ref_slug}}
    app: {{$commit_ref_slug}}
{{end}}
    deployment: {{$name}}-deployment
{{if $gitlab_deployment}}
    gitlab-deployment: {{$gitlab_deployment}}
{{end}}
data:
  aws-access-key-id: {{$aws_access_key_id}}
  aws-secret-access-key: {{$aws_secret_access_key}}
  aws-sqs-access-key-id: {{$aws_sqs_access_key_id}}
  aws-sqs-secret-access-key: {{$aws_sqs_secret_access_key}}
  django-secret-key: {{$django_secret_key}}
{{if $not_local_or_review}}
  database-user: {{$django_user}}
  database-password: {{$django_password}}
{{end}}
{{if $api_sentry_enabled}}
  api-sentry-dsn: {{$api_sentry_dsn}}
{{end}}
{{if $celery_sentry_enabled}}
  celery-sentry-dsn: {{$celery_sentry_dsn}}
{{end}}
{{if $houndigrade_sentry_enabled}}
  houndigrade-sentry-dsn: {{$houndigrade_sentry_dsn}}
{{end}}
type: Opaque
