{{/* Variables */}}
{{$prefix := or (env "DEPLOYMENT_PREFIX" | trunc 36) ""}}
{{$prefix := and $prefix (printf "-%s" $prefix)}}
{{$name := printf "%s%s" .name $prefix}}
{{$commit_ref_slug := env "CI_COMMIT_REF_SLUG"}}
{{$gitlab_deployment := env "GITLAB_DEPLOYMENT"}}

{{$api_target_port := printf "c%s-nginx" $prefix}}

{{$nginx_port := .nginx.port}}

---
kind: Service
apiVersion: v1
metadata:
  name: {{$name}}-api
  labels:
{{if $commit_ref_slug}}
    app: {{$commit_ref_slug}}
{{end}}
    deployment: {{$name}}-deployment
{{if $gitlab_deployment}}
    gitlab-deployment: {{$gitlab_deployment}}
{{end}}
spec:
  selector:
    name: {{$name}}-a
  ports:
  - name: {{$api_target_port}}
    port: 80
    protocol: TCP
    targetPort: {{$nginx_port}}
  sessionAffinity: None
  type: ClusterIP
