---
kind: Service
apiVersion: v1
metadata:
  name: {{.name}}-api
  labels:
    deployment: {{.name}}-deployment
{{if (env "GITLAB_DEPLOYMENT")}}
    gitlab-deployment: {{env "GITLAB_DEPLOYMENT"}}
{{end}}
spec:
  selector:
    name: {{.name}}-api
  ports:
  - name: nginx
    port: 80
    protocol: TCP
    targetPort: {{.nginx.port}}
  sessionAffinity: None
  type: ClusterIP
