---
kind: BuildConfig
apiVersion: v1
metadata:
  name: {{.name}}
  labels:
    deployment: {{.name}}-deployment
spec:
  failedBuildsHistoryLimit: 5
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: {{env "FRONTIGRADE_REPO_URI" | default .frontigrade.repoUri}}
      ref: {{env "FRONTIGRADE_REPO_REF" | default .frontigrade.repoUriBranch}}
  output:
    to:
      kind: ImageStreamTag
      name: {{.frontigrade.imageStreamName}}:{{.frontigrade.imageStreamTag}}
  strategy:
    type: Docker
  triggers:
  {{if ne .env "local"}}
  - github:
      secret: {{.github.secretToken | default (randAlphaNum 16)}}
    type: GitHub
  {{end}}
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
