{{$prefix := or (env "DEPLOYMENT_PREFIX") ""}}
{{if or (eq .env "local") (eq .env "review")}}
{{/* We only use buildconfigs if the environment is local, or review. */}}
---
kind: BuildConfig
apiVersion: v1
metadata:
  name: {{$prefix}}{{.name}}
  labels:
    deployment: {{$prefix}}{{.name}}-deployment
{{if (env "GITLAB_DEPLOYMENT")}}
    gitlab-deployment: {{env "GITLAB_DEPLOYMENT"}}
{{end}}
spec:
  failedBuildsHistoryLimit: 5
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: {{env "FRONTIGRADE_REPO_URI" | default .frontigrade.repoUri}}
      ref: {{env "FRONTIGRADE_REPO_REF" | default .frontigrade.repoUriBranch}}
  output:
    to:
      kind: ImageStreamTag
      name: {{$prefix}}{{.frontigrade.imageStreamName}}:{{.frontigrade.imageStreamTag}}
  strategy:
    type: Docker
  triggers:
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
{{if ne .env "local"}}
{{/* Resource limits are only relevant when we're running in OSD */}}
  resources:
    requests:
      cpu: {{.frontigrade.limits.build.cpuRequest}}
      memory: {{.frontigrade.limits.build.memRequest}}
    limits:
      cpu: {{.frontigrade.limits.build.cpuLimit}}
      memory: {{.frontigrade.limits.build.memLimit}}
{{end}}
{{end}}
