---
kind: BuildConfig
apiVersion: v1
metadata:
  name: {{if (env "DEPLOYMENT_PREFIX")}}{{env "DEPLOYMENT_PREFIX"}}-{{end}}{{.name}}
  labels:
    deployment: {{if (env "DEPLOYMENT_PREFIX")}}{{env "DEPLOYMENT_PREFIX"}}-{{end}}{{.name}}-deployment
{{if (env "GITLAB_DEPLOYMENT")}}
    gitlab-deployment: {{env "GITLAB_DEPLOYMENT"}}
{{end}}
spec:
  failedBuildsHistoryLimit: 5
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: {{env "FRONTIGRADE_REPO_URI" | default .frontigrade.repoUri}}
      ref: {{env "FRONTIGRADE_REPO_REF" | default .frontigrade.repoUriBranch}}
  output:
    to:
      kind: ImageStreamTag
      name: {{if (env "DEPLOYMENT_PREFIX")}}{{env "DEPLOYMENT_PREFIX"}}-{{end}}{{.frontigrade.imageStreamName}}:{{.frontigrade.imageStreamTag}}
  strategy:
    type: Docker
  triggers:
  {{if ne .env "local"}}
  - gitlab:
      secret: {{env "GITLAB_SECRET_TOKEN" | default .gitlab.secretToken | default (randAlphaNum 16)}}
    type: GitLab
  {{end}}
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
