{{/* We only use buildconfigs if the environment is local, or review. */}}
{{if or (eq .env "local") (eq .env "review")}}

{{/* Variables */}}
{{$prefix := or (env "DEPLOYMENT_PREFIX" | trunc 36) ""}}
{{$prefix := and $prefix (printf "-%s" $prefix)}}
{{$name := printf "%s%s" .name $prefix}}
{{$commit_ref_slug := env "CI_COMMIT_REF_SLUG"}}
{{$gitlab_deployment := env "GITLAB_DEPLOYMENT"}}

{{$frontigrade_repo_uri := ((env "FRONTIGRADE_REPO_URI") | default .frontigrade.repoUri)}}
{{$frontigrade_repo_ref := ((env "FRONTIGRADE_REPO_REF") | default .frontigrade.repoUriBranch)}}

{{$frontigrade_imagestream_name := printf "%s%s" .frontigrade.imageStreamName $prefix}}
{{$frontigrade_imagestream_tag := .frontigrade.imageStreamTag}}

{{$frontigrade_limits_build_cpu_request := .frontigrade.limits.build.cpuRequest}}
{{$frontigrade_limits_build_mem_request := .frontigrade.limits.build.memRequest}}
{{$frontigrade_limits_build_cpu_limit := .frontigrade.limits.build.cpuLimit}}
{{$frontigrade_limits_build_mem_limit := .frontigrade.limits.build.memLimit}}

{{$not_local := ne .env "local"}}
{{$not_review := ne .env "review"}}
---
kind: BuildConfig
apiVersion: v1
metadata:
  name: {{$name}}
  labels:
{{if $commit_ref_slug}}
    app: {{$commit_ref_slug}}
{{end}}
    deployment: {{$name}}-deployment
{{if $gitlab_deployment}}
    gitlab-deployment: {{$gitlab_deployment}}
{{end}}
spec:
  failedBuildsHistoryLimit: 5
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: {{$frontigrade_repo_uri}}
      ref: {{$frontigrade_repo_ref}}
  output:
    to:
      kind: ImageStreamTag
      name: {{$frontigrade_imagestream_name}}:{{$frontigrade_imagestream_tag}}
  strategy:
    type: Docker
  triggers:
{{if $not_review}}
  - type: ConfigChange
{{end}}
  - imageChange: {}
    type: ImageChange
{{if $not_local}}
{{/* Resource limits are only relevant when we're running in OSD */}}
  resources:
    requests:
      cpu: {{$frontigrade_limits_build_cpu_request}}
      memory: {{$frontigrade_limits_build_mem_request}}
    limits:
      cpu: {{$frontigrade_limits_build_cpu_limit}}
      memory: {{$frontigrade_limits_build_mem_limit}}
{{end}}
{{end}}
