{{$prefix := or (env "DEPLOYMENT_PREFIX") ""}}
---
kind: DeploymentConfig
apiVersion: v1
metadata:
  name: {{$prefix}}{{.name}}
  labels:
{{if (env "CI_ENVIRONMENT_SLUG")}}
    app: {{env "CI_ENVIRONMENT_SLUG"}}
{{end}}
    deployment: {{$prefix}}{{.name}}-deployment
{{if (env "GITLAB_DEPLOYMENT")}}
    gitlab-deployment: {{env "GITLAB_DEPLOYMENT"}}
{{end}}
spec:
  selector:
    name: {{$prefix}}{{.name}}
  replicas: {{.frontigrade.replicaCount}}
  revisionHistoryLimit: 10
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{$prefix}}{{.name}}
    spec:
      containers:
      - name: {{$prefix}}{{.name}}
{{if and (ne .env "local") (ne .env "review")}}
        image: {{env "FRONTIGRADE_IMAGE"}}
{{else}}
        image: ' '
        imagePullPolicy: Always
{{end}}
{{if ne .env "local"}}
        resources:
          requests:
            cpu: {{.frontigrade.limits.container.cpuRequest}}
            memory: {{.frontigrade.limits.container.memRequest}}
          limits:
            cpu: {{.frontigrade.limits.container.cpuLimit}}
            memory: {{.frontigrade.limits.container.memLimit}}
{{end}}
        ports:
        - containerPort: {{.frontigrade.port}}
          protocol: TCP
{{if or (eq .env "local") (eq .env "review")}}
  triggers:
    - type: "ImageChange"
      imageChangeParams:
        automatic: {{.frontigrade.enableImageChangeTrigger}}
        containerNames:
          - {{$prefix}}{{.name}}
        from:
          kind: ImageStreamTag
          name: {{$prefix}}{{.frontigrade.imageStreamName}}:{{.frontigrade.imageStreamTag}}
    - type: ConfigChange
{{end}}
