{{$prefix := or (env "DEPLOYMENT_PREFIX") ""}}
{{if and (ne .env "local") (ne .env "review")}}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{$prefix}}{{.name}}-cpu
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: DeploymentConfig
    name: {{$prefix}}{{.name}}
  minReplicas: {{.frontigrade.replicaCount}}
  maxReplicas: {{.frontigrade.replicaCountMax}}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{.frontigrade.targetAverageCPUUtilization}}
{{end}}
