{{$prefix := or (env "DEPLOYMENT_PREFIX") ""}}
{{if and (ne .env "local") (ne .env "review")}}
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{$prefix}}{{.name}}-cpu
  labels:
{{if (env "CI_COMMIT_REF_SLUG")}}
    app: {{env "CI_COMMIT_REF_SLUG"}}
{{end}}
    deployment: {{$prefix}}{{.name}}-deployment
{{if (env "GITLAB_DEPLOYMENT")}}
    gitlab-deployment: {{env "GITLAB_DEPLOYMENT"}}
{{end}}
spec:
  scaleTargetRef:
    apiVersion: v1
    kind: DeploymentConfig
    name: {{$prefix}}{{.name}}
  minReplicas: {{.frontigrade.replicaCount}}
  maxReplicas: {{.frontigrade.replicaCountMax}}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{.frontigrade.targetAverageCPUUtilization}}
{{end}}
