{{if or (eq .env "local") (eq .env "review")}}
{{$prefix := or (env "DEPLOYMENT_PREFIX") ""}}
---
kind: ImageStream
apiVersion: v1
metadata:
  name: {{$prefix}}{{.frontigrade.imageStreamName}}
  labels:
{{if (env "CI_ENVIRONMENT_SLUG")}}
    app: {{env "CI_ENVIRONMENT_SLUG"}}
{{end}}
    deployment: {{$prefix}}{{.name}}-deployment
{{if (env "GITLAB_DEPLOYMENT")}}
    gitlab-deployment: {{env "GITLAB_DEPLOYMENT"}}
{{end}}
{{end}}
