{{$prefix := or (env "DEPLOYMENT_PREFIX") ""}}
---
kind: Route
apiVersion: v1
metadata:
  name: {{$prefix}}{{.name}}
  labels:
{{if (env "CI_ENVIRONMENT_SLUG")}}
    app: {{env "CI_ENVIRONMENT_SLUG"}}
{{end}}
    deployment: {{$prefix}}{{.name}}-deployment
{{if (env "GITLAB_DEPLOYMENT")}}
    gitlab-deployment: {{env "GITLAB_DEPLOYMENT"}}
{{end}}
spec:
{{if or (env "FRONTIGRADE_ROUTE_HOST") (.frontigrade.routeHost)}}
  host: {{env "FRONTIGRADE_ROUTE_HOST" | default .frontigrade.routeHost}}
{{end}}
  path: {{env "FRONTIGRADE_ROUTE_PATH" | default .frontigrade.routePath}}
  port:
    targetPort: {{$prefix}}{{.name}}
{{if .tls}}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
{{end}}
  to:
    kind: Service
    name: {{$prefix}}{{.name}}
    weight: 100
  wildcardPolicy: None
{{if .fancyDomain}}
---
kind: Route
apiVersion: v1
metadata:
  name: {{$prefix}}{{.name}}-fancy
  annotations:
    kubernetes.io/tls-acme: {{.fancyDomainTLS | quote}}
  labels:
{{if (env "CI_ENVIRONMENT_SLUG")}}
    app: {{env "CI_ENVIRONMENT_SLUG"}}
{{end}}
    deployment: {{$prefix}}{{.name}}-deployment
{{if (env "GITLAB_DEPLOYMENT")}}
    gitlab-deployment: {{env "GITLAB_DEPLOYMENT"}}
{{end}}
spec:
  host: {{env "FRONTIGRADE_FANCY_ROUTE_PATH" | default .frontigrade.fancyRouteHost}}
  path: {{env "FRONTIGRADE_ROUTE_PATH" | default .frontigrade.routePath}}
  port:
    targetPort: {{$prefix}}{{.name}}
  to:
    kind: Service
    name: {{$prefix}}{{.name}}
    weight: 100
  wildcardPolicy: None
{{end}}
