{{/* Variables */}}
{{$prefix := or (env "DEPLOYMENT_PREFIX" | trunc 36) ""}}
{{$prefix := and $prefix (printf "-%s" $prefix)}}
{{$name := printf "%s%s" .name $prefix}}
{{$commit_ref_slug := env "CI_COMMIT_REF_SLUG"}}
{{$gitlab_deployment := env "GITLAB_DEPLOYMENT"}}

{{$frontigrade_route_host := (env "FRONTIGRADE_ROUTE_HOST" | default .frontigrade.routeHost)}}
{{$frontigrade_route_path := (env "FRONTIGRADE_ROUTE_PATH" | default .frontigrade.routePath)}}

{{$tls := .tls}}

{{$fancy_domain := .fancyDomain}}
{{$fancy_domain_tls := (.fancyDomainTLS | quote)}}
{{$frontigrade_fancy_route_host := (env "FRONTIGRADE_FANCY_ROUTE_HOST" | default .frontigrade.fancyRouteHost)}}
---
kind: Route
apiVersion: v1
metadata:
  name: {{$name}}
  labels:
{{if $commit_ref_slug}}
    app: {{$commit_ref_slug}}
{{end}}
    deployment: {{$name}}-deployment
{{if $gitlab_deployment}}
    gitlab-deployment: {{$gitlab_deployment}}
{{end}}
spec:
{{if $frontigrade_route_host}}
  host: {{$frontigrade_route_host}}
{{end}}
  path: {{$frontigrade_route_path}}
  port:
    targetPort: {{$name}}
{{if $tls}}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
{{end}}
  to:
    kind: Service
    name: {{$name}}
    weight: 100
  wildcardPolicy: None
{{if $fancy_domain}}
---
kind: Route
apiVersion: v1
metadata:
  name: {{$name}}-f
  annotations:
    kubernetes.io/tls-acme: {{$fancy_domain_tls}}
  labels:
{{if $commit_ref_slug}}
    app: {{$commit_ref_slug}}
{{end}}
    deployment: {{$name}}-deployment
{{if $gitlab_deployment}}
    gitlab-deployment: {{$gitlab_deployment}}
{{end}}
spec:
  host: {{$frontigrade_fancy_route_host}}
  path: {{$frontigrade_route_path}}
  port:
    targetPort: {{$name}}
  to:
    kind: Service
    name: {{$name}}
    weight: 100
  wildcardPolicy: None
{{end}}
