---
kind: Route
apiVersion: v1
metadata:
  name: {{.name}}
  labels:
    deployment: {{.name}}-deployment
spec:
  host: {{env "FRONTIGRADE_ROUTE_HOST" | default .frontigrade.routeHost}}
  path: {{env "FRONTIGRADE_ROUTE_PATH" | default .frontigrade.routePath}}
  port:
    targetPort: {{.name}}
  to:
    kind: Service
    name: {{.name}}
    weight: 100
  wildcardPolicy: None
