{{$prefix := or (env "DEPLOYMENT_PREFIX") ""}}
---
kind: Service
apiVersion: v1
metadata:
  name: {{$prefix}}{{.name}}
  labels:
    deployment: {{$prefix}}{{.name}}-deployment
{{if (env "GITLAB_DEPLOYMENT")}}
    gitlab-deployment: {{env "GITLAB_DEPLOYMENT"}}
{{end}}
spec:
  selector:
    name: {{$prefix}}{{.name}}
  ports:
  - name: {{$prefix}}{{.name}}
    port: 80
    protocol: TCP
    targetPort: {{.frontigrade.port}}
  sessionAffinity: None
  type: ClusterIP
